### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rcon420** [DeadSwimek/cs2-ctban#3]
01:07:08 [EROR] (cssharp:Core) Could not load plugin "/home/container/game/csgo/addons/counterstrikesharp/plugins/CTBan/CTBan.dll"
System.InvalidOperationException: Dependency resolution failed for component /home/container/game/csgo/addons/counterstrikesharp/plugins/CTBan/CTBan.dll with error code -2147450734. Detailed error: Failed to locate managed application [/home/container/game/csgo/addons/counterstrikesharp/plugins/CTBan/CTBan.dll]

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at McMaster.NETCore.Plugins.Loader.ManagedLoadContext..ctor(String mainAssemblyPath, IReadOnlyDictionary`2 managedAssemblies, IReadOnlyDictionary`2 nativeLibraries, IReadOnlyCollection`1 privateAssemblies, IReadOnlyCollection`1 defaultAssemblies, IReadOnlyCollection`1 additionalProbingPaths, IReadOnlyCollection`1 resourceProbingPaths, AssemblyLoadContext defaultLoadContext, Boolean preferDefaultLoadContext, Boolean lazyLoadReferences, Boolean isCollectible, Boolean loadInMemory, Boolean shadowCopyNativeLibraries)
   at McMaster.NETCore.Plugins.Loader.AssemblyLoadContextBuilder.Build()
   at McMaster.NETCore.Plugins.PluginLoader..ctor(PluginConfig config)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Action`1 configure)
   at McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(String assemblyFile, Type[] sharedTypes, Action`1 configure)
   at CounterStrikeSharp.API.Core.Plugin.PluginContext..ctor(IServiceProvider applicationServiceProvider, ICommandManager commandManager, IScriptHostConfiguration hostConfiguration, String path, Int32 id) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 69
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 122
   at CounterStrikeSharp.API.Core.Application.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 177

**Comment by rcon420** [comment]
plugin folder name is incorrect in the releases please :)
